Info:
  Description: appconfigserviceDev
  MpServicesBaseUrl: https://appconfigservice.tst.foo.com
  DealerServicesBaseUrl: https://appconfigservice-prdm.foo.com/v2
  ConfgurationServicesBaseUrl: https://appconfigservice-dev.apps.foo.com/api/configuration
  AuthTokenClientId: appconfigserviceUser
  AuthTokenClientSecret: ssdfsrfrgres
  AuthTokenClientGrantType: client_credentials
  MpLayer7ServicesBaseUrl: https://appconfigservice-dev.foo.com
  SpockGatewayUrl: https://appconfigserviceapigateway-dev.apps.pcfepgw.foo.com/api/proxy
  IsDevelopment: true
  Layer7Username: appconfigservice_PPLa
  Layer7Secret: NobJsA4Ve780c81Stdcesoa
